/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    FilesList: typeof import('./src/components/FilesList.vue')['default']
    Homepage: typeof import('./src/components/Homepage.vue')['default']
    MapsComponent: typeof import('./src/components/MapsComponent.vue')['default']
    MapsList: typeof import('./src/components/MapsList.vue')['default']
    MapsLoading: typeof import('./src/components/MapsLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
